# -*- coding: utf-8 -*-
"""Draw the graph

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRnRf75HygPl8KHB72d7K-9xxpKuTUqc
"""

import networkx as nx
import matplotlib.pyplot as plt

# Define the node order
node_order = [0,6,7,3,5,4,2,1]

# Create an empty graph
G = nx.Graph()

# Add nodes to the graph
for i in range(len(node_order)):
    G.add_node(node_order[i])

# Add edges to the graph
for i in range(len(node_order)-1):
    G.add_edge(node_order[i], node_order[i+1])

# Add edge from last node to first node to complete the tour
G.add_edge(node_order[-1], node_order[0])

# Draw the graph
fig, ax = plt.subplots(figsize=(8, 6))
pos = nx.spring_layout(G)
nx.draw_networkx(G, pos, with_labels=True, node_size=500, ax=ax, node_color='red')
plt.show()